FROM nginx:latest
MAINTAINER lohanyeon <yeonkh94@gmail.com>

RUN rm -rf /etc/nginx/conf.d/default.conf
ADD app.conf /etc/nginx/conf.d/app.conf

# Define mountable directories.
# VOLUME ["/data", "/etc/nginx/conf.d", "/var/log/nginx"]

# Define working directory.
# WORKDIR /etc/nginx

# Define default command.
# CMD ["/usr/sbin/nginx"]
CMD ["nginx", "-g", "daemon off;"]

# Expose ports.

EXPOSE 80
EXPOSE 443
